//Verilog generated by VPR 8.1.0-dev+e7d45e013 from post-place-and-route implementation
module top (
    input \clk ,
    input \enable ,
    input \reset ,
    output \count[0] ,
    output \count[1] ,
    output \count[2] ,
    output \count[3] ,
    output \count[4] ,
    output \count[5] ,
    output \count[6] ,
    output \count[7] ,
    output \count[8] ,
    output \count[9] ,
    output \count[10] ,
    output \count[11] ,
    output \count[12] ,
    output \count[13] ,
    output \count[14] ,
    output \count[15] 
);

    //Wires
    wire \clk_output_0_0 ;
    wire \enable_output_0_0 ;
    wire \reset_output_0_0 ;
    wire \scff_1_count_dff_Q_15_output_0_0 ;
    wire \scff_1_count_dff_Q_14_output_0_0 ;
    wire \scff_1_count_dff_Q_13_output_0_0 ;
    wire \scff_1_count_dff_Q_12_output_0_0 ;
    wire \scff_1_count_dff_Q_11_output_0_0 ;
    wire \scff_1_count_dff_Q_10_output_0_0 ;
    wire \scff_1_count_dff_Q_9_output_0_0 ;
    wire \scff_1_count_dff_Q_8_output_0_0 ;
    wire \scff_1_count_dff_Q_7_output_0_0 ;
    wire \scff_1_count_dff_Q_6_output_0_0 ;
    wire \scff_1_count_dff_Q_5_output_0_0 ;
    wire \scff_1_count_dff_Q_4_output_0_0 ;
    wire \scff_1_count_dff_Q_3_output_0_0 ;
    wire \scff_1_count_dff_Q_2_output_0_0 ;
    wire \scff_1_count_dff_Q_1_output_0_0 ;
    wire \scff_1_count_dff_Q_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_2_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_1_output_1_0 ;
    wire \frac_lut4_arith_$true_output_0_0 ;
    wire \frac_lut4_arith_$false_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_1_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_14_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_14_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_13_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_13_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_12_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_12_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_11_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_11_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_10_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_10_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_9_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_15_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_15_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_8_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_8_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_7_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_7_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_6_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_6_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_5_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_5_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_4_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_4_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_3_output_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_3_output_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_2_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_3_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_4_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_5_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_6_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_7_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_8_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_9_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_10_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_11_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_12_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_13_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_14_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_15_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_2_D_output_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_1_D_output_0_0 ;
    wire \scff_1_count_dff_Q_3_clock_0_0 ;
    wire \scff_1_count_dff_Q_4_clock_0_0 ;
    wire \scff_1_count_dff_Q_5_clock_0_0 ;
    wire \scff_1_count_dff_Q_6_clock_0_0 ;
    wire \scff_1_count_dff_Q_7_clock_0_0 ;
    wire \scff_1_count_dff_Q_8_clock_0_0 ;
    wire \scff_1_count_dff_Q_9_clock_0_0 ;
    wire \scff_1_count_dff_Q_clock_0_0 ;
    wire \scff_1_count_dff_Q_10_clock_0_0 ;
    wire \scff_1_count_dff_Q_11_clock_0_0 ;
    wire \scff_1_count_dff_Q_12_clock_0_0 ;
    wire \scff_1_count_dff_Q_13_clock_0_0 ;
    wire \scff_1_count_dff_Q_14_clock_0_0 ;
    wire \scff_1_count_dff_Q_15_clock_0_0 ;
    wire \scff_1_count_dff_Q_2_clock_0_0 ;
    wire \scff_1_count_dff_Q_1_clock_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_3_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_4_D_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_5_D_input_0_3 ;
    wire \frac_lut4_arith_count_dff_Q_6_D_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_7_D_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_8_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_9_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_10_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_11_D_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_12_D_input_0_3 ;
    wire \frac_lut4_arith_count_dff_Q_13_D_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_14_D_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_15_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_2_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_1_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_3_D_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_4_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_5_D_input_0_2 ;
    wire \frac_lut4_arith_count_dff_Q_6_D_input_0_2 ;
    wire \frac_lut4_arith_count_dff_Q_7_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_8_D_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_9_D_input_0_2 ;
    wire \frac_lut4_arith_count_dff_Q_D_input_0_2 ;
    wire \frac_lut4_arith_count_dff_Q_10_D_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_11_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_12_D_input_0_2 ;
    wire \frac_lut4_arith_count_dff_Q_13_D_input_0_2 ;
    wire \frac_lut4_arith_count_dff_Q_14_D_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_15_D_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_2_D_input_0_2 ;
    wire \frac_lut4_arith_count_dff_Q_1_D_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_15_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_15_D_input_0_3 ;
    wire \count[0]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_8_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_14_D_input_0_3 ;
    wire \count[1]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_7_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_13_D_input_0_3 ;
    wire \count[2]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_6_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_12_D_input_0_1 ;
    wire \count[3]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_5_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_11_D_input_0_2 ;
    wire \count[4]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_4_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_10_D_input_0_3 ;
    wire \count[5]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_3_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_9_D_input_0_3 ;
    wire \count[6]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_2_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_8_D_input_0_2 ;
    wire \count[7]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_1_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_7_D_input_0_3 ;
    wire \count[8]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_6_D_input_0_3 ;
    wire \count[9]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_14_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_5_D_input_0_1 ;
    wire \count[10]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_13_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_4_D_input_0_2 ;
    wire \count[11]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_12_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_3_D_input_0_3 ;
    wire \count[12]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_11_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_2_D_input_0_3 ;
    wire \count[13]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_10_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_1_D_input_0_1 ;
    wire \count[14]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_9_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_D_input_0_1 ;
    wire \count[15]_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_1_input_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_input_1_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_1_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_1_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_14_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_14_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_13_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_13_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_12_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_12_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_11_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_11_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_10_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_10_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_9_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_9_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_15_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_15_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_15_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_8_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_8_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_7_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_7_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_6_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_6_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_5_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_5_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_4_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_4_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_3_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_3_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_2_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_2_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_1_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_14_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_13_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_12_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_11_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_10_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_9_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_8_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_7_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_6_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_5_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_4_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_3_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_2_input_0_0 ;
    wire \frac_lut4_arith_count_dff_Q_7_D_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_14_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_6_D_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_13_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_5_D_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_12_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_4_D_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_11_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_3_D_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_10_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_2_D_input_0_1 ;
    wire \frac_lut4_arith_count_adder_lut4_in_9_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_1_D_input_0_3 ;
    wire \frac_lut4_arith_count_dff_Q_D_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_8_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_15_D_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_7_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_14_D_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_6_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_13_D_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_5_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_12_D_input_0_0 ;
    wire \frac_lut4_arith_count_adder_lut4_in_4_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_11_D_input_0_3 ;
    wire \frac_lut4_arith_count_adder_lut4_in_3_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_10_D_input_0_2 ;
    wire \frac_lut4_arith_count_adder_lut4_in_2_input_1_0 ;
    wire \frac_lut4_arith_count_dff_Q_9_D_input_0_1 ;
    wire \frac_lut4_arith_count_dff_Q_8_D_input_0_3 ;
    wire \scff_1_count_dff_Q_3_input_0_0 ;
    wire \scff_1_count_dff_Q_4_input_0_0 ;
    wire \scff_1_count_dff_Q_5_input_0_0 ;
    wire \scff_1_count_dff_Q_6_input_0_0 ;
    wire \scff_1_count_dff_Q_7_input_0_0 ;
    wire \scff_1_count_dff_Q_8_input_0_0 ;
    wire \scff_1_count_dff_Q_9_input_0_0 ;
    wire \scff_1_count_dff_Q_input_0_0 ;
    wire \scff_1_count_dff_Q_10_input_0_0 ;
    wire \scff_1_count_dff_Q_11_input_0_0 ;
    wire \scff_1_count_dff_Q_12_input_0_0 ;
    wire \scff_1_count_dff_Q_13_input_0_0 ;
    wire \scff_1_count_dff_Q_14_input_0_0 ;
    wire \scff_1_count_dff_Q_15_input_0_0 ;
    wire \scff_1_count_dff_Q_2_input_0_0 ;
    wire \scff_1_count_dff_Q_1_input_0_0 ;
    wire DummyOut;

    //IO assignments
    assign \count[0]  = \count[0]_input_0_0 ;
    assign \count[1]  = \count[1]_input_0_0 ;
    assign \count[2]  = \count[2]_input_0_0 ;
    assign \count[3]  = \count[3]_input_0_0 ;
    assign \count[4]  = \count[4]_input_0_0 ;
    assign \count[5]  = \count[5]_input_0_0 ;
    assign \count[6]  = \count[6]_input_0_0 ;
    assign \count[7]  = \count[7]_input_0_0 ;
    assign \count[8]  = \count[8]_input_0_0 ;
    assign \count[9]  = \count[9]_input_0_0 ;
    assign \count[10]  = \count[10]_input_0_0 ;
    assign \count[11]  = \count[11]_input_0_0 ;
    assign \count[12]  = \count[12]_input_0_0 ;
    assign \count[13]  = \count[13]_input_0_0 ;
    assign \count[14]  = \count[14]_input_0_0 ;
    assign \count[15]  = \count[15]_input_0_0 ;
    assign \clk_output_0_0  = \clk ;
    assign \enable_output_0_0  = \enable ;
    assign \reset_output_0_0  = \reset ;

    //Interconnect
    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_3_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_3_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_4_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_4_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_5_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_5_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_6_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_6_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_7_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_7_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_8_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_8_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_9_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_9_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_10_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_10_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_11_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_11_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_12_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_12_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_13_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_13_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_14_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_14_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_15_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_15_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_2_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_2_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_scff_1_count_dff_Q_1_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_1_clock_0_0 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_3_D_input_0_0  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_3_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_4_D_input_0_1  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_4_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_5_D_input_0_3  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_5_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_6_D_input_0_1  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_6_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_7_D_input_0_1  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_7_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_8_D_input_0_0  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_8_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_9_D_input_0_0  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_9_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_D_input_0_0  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_10_D_input_0_0  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_10_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_11_D_input_0_1  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_11_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_12_D_input_0_3  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_12_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_13_D_input_0_1  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_13_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_14_D_input_0_1  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_14_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_15_D_input_0_0  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_15_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_2_D_input_0_0  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_2_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_enable_output_0_0_to_frac_lut4_arith_count_dff_Q_1_D_input_0_0  (
        .datain(\enable_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_1_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_3_D_input_0_1  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_3_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_4_D_input_0_0  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_4_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_5_D_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_5_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_6_D_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_6_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_7_D_input_0_0  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_7_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_8_D_input_0_1  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_8_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_9_D_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_9_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_D_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_10_D_input_0_1  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_10_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_11_D_input_0_0  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_11_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_12_D_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_12_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_13_D_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_13_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_14_D_input_0_0  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_14_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_15_D_input_0_1  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_15_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_2_D_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_2_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_frac_lut4_arith_count_dff_Q_1_D_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_1_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_15_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_15_input_0_1  (
        .datain(\scff_1_count_dff_Q_15_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_15_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_15_output_0_0_to_frac_lut4_arith_count_dff_Q_15_D_input_0_3  (
        .datain(\scff_1_count_dff_Q_15_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_15_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_15_output_0_0_to_count[0]_input_0_0  (
        .datain(\scff_1_count_dff_Q_15_output_0_0 ),
        .dataout(\count[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_14_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_8_input_0_1  (
        .datain(\scff_1_count_dff_Q_14_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_8_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_14_output_0_0_to_frac_lut4_arith_count_dff_Q_14_D_input_0_3  (
        .datain(\scff_1_count_dff_Q_14_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_14_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_14_output_0_0_to_count[1]_input_0_0  (
        .datain(\scff_1_count_dff_Q_14_output_0_0 ),
        .dataout(\count[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_13_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_7_input_0_1  (
        .datain(\scff_1_count_dff_Q_13_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_7_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_13_output_0_0_to_frac_lut4_arith_count_dff_Q_13_D_input_0_3  (
        .datain(\scff_1_count_dff_Q_13_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_13_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_13_output_0_0_to_count[2]_input_0_0  (
        .datain(\scff_1_count_dff_Q_13_output_0_0 ),
        .dataout(\count[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_12_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_6_input_0_1  (
        .datain(\scff_1_count_dff_Q_12_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_6_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_12_output_0_0_to_frac_lut4_arith_count_dff_Q_12_D_input_0_1  (
        .datain(\scff_1_count_dff_Q_12_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_12_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_12_output_0_0_to_count[3]_input_0_0  (
        .datain(\scff_1_count_dff_Q_12_output_0_0 ),
        .dataout(\count[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_11_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_5_input_0_1  (
        .datain(\scff_1_count_dff_Q_11_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_5_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_11_output_0_0_to_frac_lut4_arith_count_dff_Q_11_D_input_0_2  (
        .datain(\scff_1_count_dff_Q_11_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_11_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_11_output_0_0_to_count[4]_input_0_0  (
        .datain(\scff_1_count_dff_Q_11_output_0_0 ),
        .dataout(\count[4]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_10_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_4_input_0_1  (
        .datain(\scff_1_count_dff_Q_10_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_4_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_10_output_0_0_to_frac_lut4_arith_count_dff_Q_10_D_input_0_3  (
        .datain(\scff_1_count_dff_Q_10_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_10_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_10_output_0_0_to_count[5]_input_0_0  (
        .datain(\scff_1_count_dff_Q_10_output_0_0 ),
        .dataout(\count[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_9_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_3_input_0_1  (
        .datain(\scff_1_count_dff_Q_9_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_3_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_9_output_0_0_to_frac_lut4_arith_count_dff_Q_9_D_input_0_3  (
        .datain(\scff_1_count_dff_Q_9_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_9_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_9_output_0_0_to_count[6]_input_0_0  (
        .datain(\scff_1_count_dff_Q_9_output_0_0 ),
        .dataout(\count[6]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_8_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_2_input_0_1  (
        .datain(\scff_1_count_dff_Q_8_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_2_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_8_output_0_0_to_frac_lut4_arith_count_dff_Q_8_D_input_0_2  (
        .datain(\scff_1_count_dff_Q_8_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_8_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_8_output_0_0_to_count[7]_input_0_0  (
        .datain(\scff_1_count_dff_Q_8_output_0_0 ),
        .dataout(\count[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_7_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_1_input_0_1  (
        .datain(\scff_1_count_dff_Q_7_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_1_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_7_output_0_0_to_frac_lut4_arith_count_dff_Q_7_D_input_0_3  (
        .datain(\scff_1_count_dff_Q_7_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_7_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_7_output_0_0_to_count[8]_input_0_0  (
        .datain(\scff_1_count_dff_Q_7_output_0_0 ),
        .dataout(\count[8]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_6_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_input_0_1  (
        .datain(\scff_1_count_dff_Q_6_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_6_output_0_0_to_frac_lut4_arith_count_dff_Q_6_D_input_0_3  (
        .datain(\scff_1_count_dff_Q_6_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_6_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_6_output_0_0_to_count[9]_input_0_0  (
        .datain(\scff_1_count_dff_Q_6_output_0_0 ),
        .dataout(\count[9]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_5_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_14_input_0_1  (
        .datain(\scff_1_count_dff_Q_5_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_14_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_5_output_0_0_to_frac_lut4_arith_count_dff_Q_5_D_input_0_1  (
        .datain(\scff_1_count_dff_Q_5_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_5_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_5_output_0_0_to_count[10]_input_0_0  (
        .datain(\scff_1_count_dff_Q_5_output_0_0 ),
        .dataout(\count[10]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_4_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_13_input_0_1  (
        .datain(\scff_1_count_dff_Q_4_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_13_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_4_output_0_0_to_frac_lut4_arith_count_dff_Q_4_D_input_0_2  (
        .datain(\scff_1_count_dff_Q_4_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_4_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_4_output_0_0_to_count[11]_input_0_0  (
        .datain(\scff_1_count_dff_Q_4_output_0_0 ),
        .dataout(\count[11]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_3_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_12_input_0_1  (
        .datain(\scff_1_count_dff_Q_3_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_12_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_3_output_0_0_to_frac_lut4_arith_count_dff_Q_3_D_input_0_3  (
        .datain(\scff_1_count_dff_Q_3_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_3_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_3_output_0_0_to_count[12]_input_0_0  (
        .datain(\scff_1_count_dff_Q_3_output_0_0 ),
        .dataout(\count[12]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_2_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_11_input_0_1  (
        .datain(\scff_1_count_dff_Q_2_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_11_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_2_output_0_0_to_frac_lut4_arith_count_dff_Q_2_D_input_0_3  (
        .datain(\scff_1_count_dff_Q_2_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_2_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_2_output_0_0_to_count[13]_input_0_0  (
        .datain(\scff_1_count_dff_Q_2_output_0_0 ),
        .dataout(\count[13]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_1_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_10_input_0_1  (
        .datain(\scff_1_count_dff_Q_1_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_10_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_1_output_0_0_to_frac_lut4_arith_count_dff_Q_1_D_input_0_1  (
        .datain(\scff_1_count_dff_Q_1_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_1_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_1_output_0_0_to_count[14]_input_0_0  (
        .datain(\scff_1_count_dff_Q_1_output_0_0 ),
        .dataout(\count[14]_input_0_0 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_9_input_0_1  (
        .datain(\scff_1_count_dff_Q_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_9_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_output_0_0_to_frac_lut4_arith_count_dff_Q_D_input_0_1  (
        .datain(\scff_1_count_dff_Q_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_scff_1_count_dff_Q_output_0_0_to_count[15]_input_0_0  (
        .datain(\scff_1_count_dff_Q_output_0_0 ),
        .dataout(\count[15]_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_2_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_1_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_2_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_1_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_1_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_1_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_1_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_1_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_1_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_1_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_14_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_14_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_14_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_14_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_13_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_13_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_13_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_13_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_12_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_12_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_12_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_12_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_11_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_11_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_11_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_11_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_10_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_10_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_10_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_10_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_9_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_9_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_9_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_9_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_15_input_0_0  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_15_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_15_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_15_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_15_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_15_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_8_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_8_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_8_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_8_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_7_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_7_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_7_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_7_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_6_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_6_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_6_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_6_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_5_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_5_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_5_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_5_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_4_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_4_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_4_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_4_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_3_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_3_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_3_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_3_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_2_input_0_2  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_2_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$true_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_2_input_0_3  (
        .datain(\frac_lut4_arith_$true_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_2_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_1_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_1_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_14_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_14_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_13_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_13_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_12_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_12_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_11_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_11_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_10_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_10_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_9_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_9_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_8_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_8_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_7_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_7_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_6_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_6_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_5_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_5_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_4_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_4_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_3_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_3_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_$false_output_0_0_to_frac_lut4_arith_count_adder_lut4_in_2_input_0_0  (
        .datain(\frac_lut4_arith_$false_output_0_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_2_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_1_output_0_0_to_frac_lut4_arith_count_dff_Q_7_D_input_0_2  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_1_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_7_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_14_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_14_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_output_0_0_to_frac_lut4_arith_count_dff_Q_6_D_input_0_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_6_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_14_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_13_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_14_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_13_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_14_output_0_0_to_frac_lut4_arith_count_dff_Q_5_D_input_0_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_14_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_5_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_13_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_12_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_13_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_12_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_13_output_0_0_to_frac_lut4_arith_count_dff_Q_4_D_input_0_3  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_13_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_4_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_12_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_11_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_12_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_11_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_12_output_0_0_to_frac_lut4_arith_count_dff_Q_3_D_input_0_2  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_12_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_3_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_11_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_10_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_11_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_10_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_11_output_0_0_to_frac_lut4_arith_count_dff_Q_2_D_input_0_1  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_11_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_2_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_10_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_9_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_10_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_9_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_10_output_0_0_to_frac_lut4_arith_count_dff_Q_1_D_input_0_3  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_10_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_1_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_9_output_0_0_to_frac_lut4_arith_count_dff_Q_D_input_0_3  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_9_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_15_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_8_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_15_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_8_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_15_output_0_0_to_frac_lut4_arith_count_dff_Q_15_D_input_0_2  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_15_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_15_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_8_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_7_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_8_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_7_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_8_output_0_0_to_frac_lut4_arith_count_dff_Q_14_D_input_0_2  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_8_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_14_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_7_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_6_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_7_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_6_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_7_output_0_0_to_frac_lut4_arith_count_dff_Q_13_D_input_0_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_7_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_13_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_6_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_5_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_6_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_5_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_6_output_0_0_to_frac_lut4_arith_count_dff_Q_12_D_input_0_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_6_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_12_D_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_5_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_4_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_5_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_4_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_5_output_0_0_to_frac_lut4_arith_count_dff_Q_11_D_input_0_3  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_5_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_11_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_4_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_3_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_4_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_3_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_4_output_0_0_to_frac_lut4_arith_count_dff_Q_10_D_input_0_2  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_4_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_10_D_input_0_2 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_3_output_1_0_to_frac_lut4_arith_count_adder_lut4_in_2_input_1_0  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_3_output_1_0 ),
        .dataout(\frac_lut4_arith_count_adder_lut4_in_2_input_1_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_3_output_0_0_to_frac_lut4_arith_count_dff_Q_9_D_input_0_1  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_3_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_9_D_input_0_1 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_adder_lut4_in_2_output_0_0_to_frac_lut4_arith_count_dff_Q_8_D_input_0_3  (
        .datain(\frac_lut4_arith_count_adder_lut4_in_2_output_0_0 ),
        .dataout(\frac_lut4_arith_count_dff_Q_8_D_input_0_3 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_3_D_output_0_0_to_scff_1_count_dff_Q_3_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_3_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_3_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_4_D_output_0_0_to_scff_1_count_dff_Q_4_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_4_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_4_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_5_D_output_0_0_to_scff_1_count_dff_Q_5_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_5_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_5_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_6_D_output_0_0_to_scff_1_count_dff_Q_6_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_6_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_6_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_7_D_output_0_0_to_scff_1_count_dff_Q_7_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_7_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_7_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_8_D_output_0_0_to_scff_1_count_dff_Q_8_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_8_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_8_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_9_D_output_0_0_to_scff_1_count_dff_Q_9_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_9_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_9_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_D_output_0_0_to_scff_1_count_dff_Q_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_10_D_output_0_0_to_scff_1_count_dff_Q_10_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_10_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_10_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_11_D_output_0_0_to_scff_1_count_dff_Q_11_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_11_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_11_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_12_D_output_0_0_to_scff_1_count_dff_Q_12_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_12_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_12_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_13_D_output_0_0_to_scff_1_count_dff_Q_13_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_13_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_13_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_14_D_output_0_0_to_scff_1_count_dff_Q_14_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_14_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_14_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_15_D_output_0_0_to_scff_1_count_dff_Q_15_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_15_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_15_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_2_D_output_0_0_to_scff_1_count_dff_Q_2_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_2_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_2_input_0_0 )
    );

    fpga_interconnect \routing_segment_frac_lut4_arith_count_dff_Q_1_D_output_0_0_to_scff_1_count_dff_Q_1_input_0_0  (
        .datain(\frac_lut4_arith_count_dff_Q_1_D_output_0_0 ),
        .dataout(\scff_1_count_dff_Q_1_input_0_0 )
    );


    //Cell instances
    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_1  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_1_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_1_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_1_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_1_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_1_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_1_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_1_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_14  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_14_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_14_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_14_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_14_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_14_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_14_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_14_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_13  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_13_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_13_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_13_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_13_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_13_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_13_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_13_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_12  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_12_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_12_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_12_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_12_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_12_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_12_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_12_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_11  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_11_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_11_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_11_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_11_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_11_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_11_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_11_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_10  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_10_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_10_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_10_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_10_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_10_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_10_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_10_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_9  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_9_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_9_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_9_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_9_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_9_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_9_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001000001100110),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_15  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_15_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_15_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_15_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_15_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_15_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_15_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_8  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_8_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_8_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_8_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_8_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_8_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_8_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_8_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_7  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_7_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_7_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_7_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_7_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_7_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_7_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_7_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_6  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_6_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_6_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_6_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_6_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_6_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_6_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_6_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_5  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_5_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_5_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_5_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_5_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_5_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_5_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_5_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_4  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_4_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_4_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_4_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_4_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_4_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_4_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_4_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_3  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_3_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_3_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_3_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_3_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_3_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_3_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_3_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001011001101001),
        .MODE(1)
    ) \frac_lut4_arith_count_adder_lut4_in_2  (
        .cin(\frac_lut4_arith_count_adder_lut4_in_2_input_1_0 ),
        .in({
            \frac_lut4_arith_count_adder_lut4_in_2_input_0_3 ,
            \frac_lut4_arith_count_adder_lut4_in_2_input_0_2 ,
            \frac_lut4_arith_count_adder_lut4_in_2_input_0_1 ,
            \frac_lut4_arith_count_adder_lut4_in_2_input_0_0 }),
        .cout(\frac_lut4_arith_count_adder_lut4_in_2_output_1_0 ),
        .lut4_out(\frac_lut4_arith_count_adder_lut4_in_2_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0000010010001100),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_3_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_3_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_3_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_3_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_3_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_3_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_3  (
        .D(\scff_1_count_dff_Q_3_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_3_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_3_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0000100000101010),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_4_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_4_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_4_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_4_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_4_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_4_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_4  (
        .D(\scff_1_count_dff_Q_4_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_4_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_4_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0011000001010000),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_5_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_5_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_5_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_5_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_5_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_5_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_5  (
        .D(\scff_1_count_dff_Q_5_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_5_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_5_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001000011010000),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_6_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_6_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_6_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_6_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_6_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_6_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_6  (
        .D(\scff_1_count_dff_Q_6_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_6_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_6_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0000001010001010),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_7_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_7_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_7_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_7_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_7_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_7_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_7  (
        .D(\scff_1_count_dff_Q_7_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_7_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_7_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0000100001001100),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_8_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_8_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_8_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_8_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_8_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_8_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_8  (
        .D(\scff_1_count_dff_Q_8_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_8_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_8_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001000010110000),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_9_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_9_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_9_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_9_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_9_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_9_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_9  (
        .D(\scff_1_count_dff_Q_9_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_9_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_9_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0010000001110000),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q  (
        .D(\scff_1_count_dff_Q_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0000010010001100),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_10_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_10_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_10_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_10_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_10_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_10_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_10  (
        .D(\scff_1_count_dff_Q_10_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_10_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_10_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0000100000101010),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_11_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_11_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_11_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_11_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_11_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_11_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_11  (
        .D(\scff_1_count_dff_Q_11_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_11_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_11_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0011000001010000),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_12_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_12_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_12_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_12_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_12_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_12_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_12  (
        .D(\scff_1_count_dff_Q_12_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_12_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_12_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001000011010000),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_13_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_13_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_13_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_13_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_13_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_13_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_13  (
        .D(\scff_1_count_dff_Q_13_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_13_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_13_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0000001010001010),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_14_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_14_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_14_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_14_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_14_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_14_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_14  (
        .D(\scff_1_count_dff_Q_14_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_14_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_14_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0000010010001100),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_15_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_15_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_15_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_15_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_15_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_15_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_15  (
        .D(\scff_1_count_dff_Q_15_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_15_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_15_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0001000010110000),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_2_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_2_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_2_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_2_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_2_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_2_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_2  (
        .D(\scff_1_count_dff_Q_2_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_2_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_2_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0010000001110000),
        .MODE(0)
    ) \frac_lut4_arith_count_dff_Q_1_D  (
        .cin(1'b0),
        .in({
            \frac_lut4_arith_count_dff_Q_1_D_input_0_3 ,
            \frac_lut4_arith_count_dff_Q_1_D_input_0_2 ,
            \frac_lut4_arith_count_dff_Q_1_D_input_0_1 ,
            \frac_lut4_arith_count_dff_Q_1_D_input_0_0 }),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_count_dff_Q_1_D_output_0_0 )
    );

    scff_1 #(
        .MODE(1)
    ) \scff_1_count_dff_Q_1  (
        .D(\scff_1_count_dff_Q_1_input_0_0 ),
        .DI(1'b0),
        .clk(\scff_1_count_dff_Q_1_clock_0_0 ),
        .preset(1'b0),
        .reset(1'b0),
        .Q(\scff_1_count_dff_Q_1_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(0000000000000000),
        .MODE(0)
    ) \frac_lut4_arith_$false  (
        .cin(1'b0),
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0}),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_$false_output_0_0 )
    );

    frac_lut4_arith #(
        .LUT(1111111111111111),
        .MODE(0)
    ) \frac_lut4_arith_$true  (
        .cin(1'b0),
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0}),
        .cout(DummyOut),
        .lut4_out(\frac_lut4_arith_$true_output_0_0 )
    );


endmodule
