#!/bin/bash
set -e

MYPATH=$(dirname "$(readlink -f "$BASH_SOURCE")")


source ${MYPATH}/env

JLINK2BINARY=`readlink -f ${MYPATH}/../bin/python/bitstream_to_binary.py`


python3 ${JLINK2BINARY} ${TOP_F}.bit ../${TOP_F}.bin
