#!/bin/bash
set -e

MYPATH=`realpath $0`
MYPATH=`dirname ${MYPATH}`

PCF=$1
EBLIF=$2
NET=$3
PART=$4
DEVICE=$5
ARCH_DEF=$6

if [[ "$DEVICE" =~ ^(qlf_k4n8_qlf_k4n8)$ ]];then
	DEVICE_1="qlf_k4n8-qlf_k4n8_umc22"
	PINMAPXML="pinmap_qlf_k4n8_umc22.xml"
	INTERFACEXML="interface-mapping_24x24.xml"
	PINMAPCSV="qlf_k4n8-qlf_k4n8_umc22_24x24.csv"
	DEV="qlf_k4n8_umc22"
else
    DEVICE_1=${DEVICE}
fi

ARCH_DIR=`realpath ${MYPATH}/../share/symbiflow/arch/${DEVICE_1}_${DEVICE_1}`
PINMAP_XML=`realpath ${ARCH_DIR}/${PINMAPXML}`
INTF_XML=`realpath ${ARCH_DIR}/lib/${INTERFACEXML}`
PINMAP_CSV=`realpath ${ARCH_DIR}/lib/${PINMAPCSV}`
IOGEN=`realpath ${MYPATH}/python/create_ioplace.py`
CREATE_LIB=`realpath ${MYPATH}/python/create_lib.py`
PROJECT=$(basename -- "$EBLIF")
IOPLACE_FILE="${PROJECT%.*}_io.place"

python3 ${IOGEN} --pcf $PCF --blif $EBLIF --pinmap_xml $PINMAP_XML --csv_file $PART --net $NET > ${IOPLACE_FILE}
python3 ${CREATE_LIB} -n ${DEV}_te_OP72_SSM40 -m $DEVICE_1 -c $PINMAP_CSV -x $INTF_XML -d qlf_k4n8 -t ${ARCH_DIR}/lib
